apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "arypodr.fullname" . }}-db
  labels:
    {{- include "arypodr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.db.storageClassName }}
  storageClassName: {{ .Values.persistence.db.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.db.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "arypodr.fullname" . }}-media
  labels:
    {{- include "arypodr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.media.storageClassName }}
  storageClassName: {{ .Values.persistence.media.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
