apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arypodr.fullname" . }}
  labels:
    {{- include "arypodr.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
