apiVersion: v1
kind: Service
metadata:
  name: {{ include "arypodr.fullname" . }}
  labels:
    {{- include "arypodr.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "arypodr.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  type: {{ .Values.service.type }}
